name: CI

env:
  FOO: "bar"

on:
  workflow_dispatch:
    inputs:
      foo:
        description: "bar"
        required: false
        default: ${FOO}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: echo env
        env:
          FOOBAR: ${{ inputs.foo || env.FOO }}
        run: echo ${FOOBAR}

      - name: echo 2
        env:
          FOOBAR: ${ ${{ inputs.foo }}:-$FOO} 
        run: echo ${FOOBAR}

      - name: CPU
        run: cat /proc/cpuinfo
        
      - name: SSD
        run: |
          sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
          sudo /sbin/sysctl -w vm.drop_caches=3
          dd if=tempfile of=/dev/null bs=1M count=1024
