name: CI

env:
  FOO: "bar"

on:
  workflow_dispatch:
    inputs:
      foo:
        description: "bar"
        required: false
        default: ${FOO}
      foo2:
        description: "bar2"
        required: false
        default: ${FOO}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set fu 1
        run: echo "FOOBAR=${{ inputs.foo || env.FOO }}" >> $GITHUB_ENV
      - name: echo env 1
        run: echo $FOOBAR

      - name: set fu 2
        run: echo "FOOBAR=${{ inputs.foo2 || env.FOO }}" >> $GITHUB_ENV
      - name: echo env 2
        run: echo $FOOBAR

      - name: CPU
        run: cat /proc/cpuinfo
        
      - name: SSD
        run: |
          sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
          sudo /sbin/sysctl -w vm.drop_caches=3
          dd if=tempfile of=/dev/null bs=1M count=1024
