name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CPU
        run: cat /proc/cpuinfo
        
      - name: SSD
        run: |
          sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
          sudo /sbin/sysctl -w vm.drop_caches=3
          dd if=tempfile of=/dev/null bs=1M count=1024
